Adding unlimited pagination
mongerinc/search-request pull request #24
Opened 2017-12-22 03:03 UTC by sdsomma

Pagination can now be ignored by setting the search request to unlimited.

2017-12-22 03:18 UTC, janhartigan requested changes
There should probably be a way to reverse this. What would be good enough, I think, is to always set `unlimited` to false whenever you set the `limit()`

2017-12-22 03:18 UTC, janhartigan commented on README.md
> +The unlimited feature is only a falg. Your database query applier must check for this with the `isUnlimited()` method to support this feature.
falg

2017-12-22 03:18 UTC, janhartigan commented
Also needs js counterpart if you aren't already doing it

2017-12-22 03:21 UTC, sdsomma commented
i started making deeply tied to page and limit.. then it got a little weird.. so i decided to make it a flag that unrelated to pagination.. the applier can decide if it wants to use it or not.. else you can potentially get someone from fronted send unlimited on a request that you would not want to allow... you can unset it by ->unlimited(false)

2017-12-22 03:22 UTC, sdsomma commented
but yea.. maybe setting a limit or page should mark unlimited as false.. makes sense

2017-12-22 03:26 UTC, sdsomma commented
js comming

2017-12-22 04:24 UTC, janhartigan requested changes

2017-12-22 04:24 UTC, janhartigan commented on src/SearchRequest.php
> +		$this->limit($inputs['limit']);
I think this creates a failing test scenario:

```
$originalRequest = SearchRequest::create()->limit(1)->unlimited();
$newRequest = SearchRequest::create($originalRequest->toJson());

$this->assertTrue($newRequest->isUnlimited());
```

2017-12-26 18:43 UTC, janhartigan approved these changes

2017-12-26 18:45 UTC, merged